apiVersion: 1

datasources:
  - name: SensorSentinel
    type: postgres
    url: postgres:5432
    database: sensorsentinel
    user: sensorsentinel
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
